Repository KTH-96/issue-tracker, pull requests merged in 2022-06, with the labels that each got.

#2 Chore: 초기 환경 세팅
  FE/.eslintrc.js
  FE/.gitignore
  FE/.prettierrc
  FE/package-lock.json
  FE/package.json
  FE/public/index.html
  FE/src/App.tsx
  FE/src/index.tsx
  FE/tsconfig.json
  FE/webpack.config.js
Labels: FE, chore

#13 Feature 4 로그인 페이지 아이디 비밀번호로 로그인
  FE/src/App.tsx
  FE/src/assets/icons/Icon.tsx
  FE/src/assets/icons/svgs/index.tsx
  FE/src/common/Button.tsx
  FE/src/common/TextInput.tsx
  FE/src/constants/index.ts
  FE/src/login/LoginPage.tsx
  FE/tsconfig.json
  FE/webpack.config.js
Labels: FE, feat

#16 Feature 12 1주차 수요일 리뷰 반영
  FE/.eslintrc.js
  FE/src/GlobalStyles.tsx
  FE/src/assets/icons/svgs/index.ts
  FE/webpack.config.js
Labels: FE, refactor, chore

#18 Feature 17 아이디로 로그인 에러 메시지 안 사라짐
  FE/src/common/TextInput.tsx
  FE/src/login/LoginPage.tsx
Labels: bug

#22 Feature 21 1주차 금요일 리뷰 반영
  FE/.babelrc
  FE/.eslintrc
  FE/.eslintrc.js
  FE/config/webpack.common.js
  FE/config/webpack.dev.js
  FE/config/webpack.prod.js
  FE/package-lock.json
  FE/package.json
  FE/src/App.tsx
  FE/src/assets/icons/Icon.tsx
  FE/src/assets/icons/svgs/index.ts
  FE/src/common/Button.tsx
  FE/src/common/TextInput.tsx
  FE/src/constants/colors.ts
  FE/src/constants/greyscale.ts
  FE/src/constants/index.ts
  FE/src/login/Login.tsx
  FE/src/login/LoginPage.tsx
  FE/src/theme.ts
  FE/tsconfig.json
  FE/webpack.config.js
Labels: FE, refactor, chore

#24 이슈 목록 UI - 이슈 목록 박스, 이슈 목록 아이템
  FE/config/webpack.dev.js
  FE/config/webpack.prod.js
  FE/src/assets/icons/svgs/alertCircle.svg
  FE/src/assets/icons/svgs/archive.svg
  FE/src/assets/icons/svgs/arrowBottom.svg
  FE/src/assets/icons/svgs/checkBoxActive.svg
  FE/src/assets/icons/svgs/checkBoxDisable.svg
  FE/src/assets/icons/svgs/checkBoxInitial.svg
  FE/src/assets/icons/svgs/chevronDown.svg
  FE/src/assets/icons/svgs/index.ts
  FE/src/common/FilterBar.tsx
  FE/src/issueList/CheckBox.tsx
  FE/src/issueList/EmptyIssueItem.tsx
  FE/src/issueList/IssueHeader.tsx
  FE/src/issueList/IssueItem.tsx
  FE/src/issueList/IssueListPage.tsx
  FE/src/issueList/IssueMenu.tsx
  FE/src/issueList/IssueTab.tsx
  FE/src/issueList/Label.tsx
Labels: FE, design

#26 Feature 5 이슈 목록 UI
  FE/config/webpack.dev.js
  FE/config/webpack.prod.js
  FE/src/App.tsx
  FE/src/assets/icons/Icon.tsx
  FE/src/assets/icons/svgs/alertCircle.svg
  FE/src/assets/icons/svgs/archive.svg
  FE/src/assets/icons/svgs/checkBoxActive.svg
  FE/src/assets/icons/svgs/checkBoxDisable.svg
  FE/src/assets/icons/svgs/checkBoxInitial.svg
  FE/src/assets/icons/svgs/chevronDown.svg
  FE/src/assets/icons/svgs/index.ts
  FE/src/assets/icons/svgs/milestone.svg
  FE/src/assets/icons/svgs/plus.svg
  FE/src/assets/icons/svgs/search.svg
  FE/src/assets/icons/svgs/tag.svg
  FE/src/common/ButtonSmallStandard.tsx
  FE/src/common/FilterBar.tsx
  FE/src/common/Layout.tsx
  FE/src/common/Tap.tsx
  FE/src/common/Taps.tsx
  FE/src/issueList/CheckBox.tsx
  FE/src/issueList/EmptyIssueItem.tsx
  FE/src/issueList/IssueHeader.tsx
  FE/src/issueList/IssueItem.tsx
  FE/src/issueList/IssueListPage.tsx
  FE/src/issueList/IssueMenu.tsx
  FE/src/issueList/IssueTab.tsx
  FE/src/issueList/Label.tsx
Labels: FE, design

#29 Feature 7 - 이슈 목록 - 이슈 목록에서 분기하는 페이지 라우터 설정
  FE/package-lock.json
  FE/package.json
  FE/src/App.tsx
  FE/src/addIssue/AddIssuePage.tsx
  FE/src/common/Tap.tsx
  FE/src/common/Taps.tsx
  FE/src/index.tsx
  FE/src/issueDetail/IssueDetailPage.tsx
  FE/src/issueList/IssueItem.tsx
  FE/src/issueList/IssueListPage.tsx
  FE/src/labelList/LabelListPage.tsx
  FE/src/milestoneList/MilestoneListPage.tsx
Labels: FE, feat

#31 Feature 25
  BE/src/main/java/kr/codesquad/issuetracker/auth/GithubOauth.java
  BE/src/main/java/kr/codesquad/issuetracker/auth/JwtInterceptor.java
  BE/src/main/java/kr/codesquad/issuetracker/auth/annotation/LoginRequired.java
  BE/src/main/java/kr/codesquad/issuetracker/auth/annotation/LoginVerifyResolver.java
  BE/src/main/java/kr/codesquad/issuetracker/auth/service/JwtService.java
  BE/src/main/java/kr/codesquad/issuetracker/auth/utils/Utils.java
  BE/src/main/java/kr/codesquad/issuetracker/config/WebConfig.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/image/Image.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/label/Color.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/label/Label.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/label/repository/LabelRepository.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/member/Member.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/member/repository/MemberRepository.java
  BE/src/main/java/kr/codesquad/issuetracker/domain/milestone/repository/MilestoneRepository.java
  BE/src/main/java/kr/codesquad/issuetracker/exception/ErrorMessage.java
  BE/src/main/java/kr/codesquad/issuetracker/service/LabelService.java
  BE/src/main/java/kr/codesquad/issuetracker/service/MemberService.java
  BE/src/main/java/kr/codesquad/issuetracker/web/controller/LabelController.java
  BE/src/main/java/kr/codesquad/issuetracker/web/dto/label/LabelDto.java
  BE/src/main/java/kr/codesquad/issuetracker/web/dto/label/LabelRequestDto.java
  BE/src/main/java/kr/codesquad/issuetracker/web/dto/label/LabelResponseDto.java
  BE/src/main/resources/data.sql
Labels: BE

#34 Feature 27 이슈목록 다중 선택
  FE/.prettierrc
  FE/package-lock.json
  FE/package.json
  FE/src/assets/icons/Icon.tsx
  FE/src/issueList/CheckBox.tsx
  FE/src/issueList/EmptyIssueItem.tsx
  FE/src/issueList/IssueHeader.tsx
  FE/src/issueList/IssueItem.tsx
  FE/src/issueList/IssueList.tsx
  FE/src/issueList/IssueListPage.tsx
  FE/src/issueList/IssueMenu.tsx
  FE/src/issueList/Label.tsx
  FE/src/utils.ts
Labels: FE, feat

#35 Feature 28 이슈목록 필터 드롭다운 기능 구현
  FE/src/common/ DropDownCheckBoxItem.tsx
  FE/src/common/ DropDownPanel.tsx
  FE/src/common/ButtonSmallStandard.tsx
  FE/src/issueList/FilterBar.tsx
  FE/src/issueList/IssueHeader.tsx
  FE/src/issueList/IssueMenu.tsx
  FE/src/issueList/IssueTab.tsx
  FE/src/login/Login.tsx
Labels: FE, feat

#39 Yellow 2주차 금요일 리뷰 반영
  FE/src/common/DropDownPanel.tsx
  FE/src/issueList/FilterBar.tsx
Labels: FE, refactor

#40 2주차 금요일 리뷰 반영 - 이슈 목록 부분
  FE/package-lock.json
  FE/package.json
  FE/public/mockServiceWorker.js
  FE/src/index.tsx
  FE/src/issueList/ClickedIssueHeader.tsx
  FE/src/issueList/IssueHeader.tsx
  FE/src/issueList/IssueItem.tsx
  FE/src/issueList/IssueList.tsx
  FE/src/issueList/IssueListPage.tsx
  FE/src/issueList/IssueListProvider.tsx
  FE/src/issueList/checkReducer.tsx
  FE/src/mocks/browser.ts
  FE/src/mocks/handlers.ts
  FE/src/mocks/issueListData.js
  FE/tsconfig.json
Labels: FE, refactor

#41 Feature 38 2주차 금요일 리뷰 반영
  FE/package-lock.json
  FE/package.json
  FE/public/mockServiceWorker.js
  FE/src/common/DropDownPanel.tsx
  FE/src/index.tsx
  FE/src/issueList/ClickedIssueHeader.tsx
  FE/src/issueList/FilterBar.tsx
  FE/src/issueList/IssueHeader.tsx
  FE/src/issueList/IssueItem.tsx
  FE/src/issueList/IssueList.tsx
  FE/src/issueList/IssueListPage.tsx
  FE/src/issueList/IssueListProvider.tsx
  FE/src/issueList/checkReducer.tsx
  FE/src/mocks/browser.ts
  FE/src/mocks/handlers.ts
  FE/src/mocks/issueListData.js
  FE/tsconfig.json
Labels: FE, refactor

#44 Feature 42 이슈 목록 react query로 데이터 가져오기
  FE/src/App.tsx
  FE/src/assets/icons/Icon.tsx
  FE/src/issueList/CheckBox.tsx
  FE/src/issueList/ClickedIssueHeader.tsx
  FE/src/issueList/IssueHeader.tsx
  FE/src/issueList/IssueItem.tsx
  FE/src/issueList/IssueList.tsx
  FE/src/issueList/IssueMenu.tsx
  FE/src/issueList/checkReducer.tsx
  FE/src/mocks/issueListData.js
  FE/src/pages/AddIssuePage.tsx
  FE/src/pages/IssueDetailPage.tsx
  FE/src/pages/LabelListPage.tsx
  FE/src/pages/MilestoneListPage.tsx
Labels: FE, refactor

#46 이슈 헤더 필터옵션 데이터 반영
  FE/package-lock.json
  FE/package.json
  FE/src/common/DropDownPanel.tsx
  FE/src/index.tsx
  FE/src/issueList/IssueHeader.tsx
  FE/src/issueList/IssueTab.tsx
  FE/src/mocks/handlers.ts
  FE/src/mocks/issueFilterOptions.js
  FE/src/utils.ts
Labels: FE, feat

#47 Feature 45 이슈 헤더 필터옵션 데이터 가져오기
  FE/package-lock.json
  FE/package.json
  FE/src/App.tsx
  FE/src/common/components/Layout.tsx
  FE/src/common/components/Tab.tsx
  FE/src/common/components/TextInput.tsx
  FE/src/common/components/buttons/Button.tsx
  FE/src/common/components/buttons/ButtonSmallStandard.tsx
  FE/src/common/components/dropDown/DropDownCheckBoxItem.tsx
  FE/src/common/components/dropDown/DropDownPanel.tsx
  FE/src/common/constants/colors.ts
  FE/src/common/constants/greyscale.ts
  FE/src/common/constants/index.ts
  FE/src/common/utils/utils.ts
  FE/src/index.tsx
  FE/src/issueList/FilterBar.tsx
  FE/src/issueList/IssueTab.tsx
  FE/src/issueList/LinkTabs.tsx
  FE/src/issueList/issueListTable/CheckBox.tsx
  FE/src/issueList/issueListTable/IssueList.tsx
  FE/src/issueList/issueListTable/issueHeader/ClickedIssueHeader.tsx
  FE/src/issueList/issueListTable/issueHeader/IssueHeader.tsx
  FE/src/issueList/issueListTable/issueHeader/IssueMenu.tsx
  FE/src/issueList/issueListTable/issueHeader/IssueTab.tsx
  FE/src/issueList/issueListTable/issueItem/EmptyIssueItem.tsx
  FE/src/issueList/issueListTable/issueItem/IssueItem.tsx
  FE/src/issueList/issueListTable/issueItem/Label.tsx
  FE/src/issueList/stores/IssueListProvider.tsx
  FE/src/issueList/stores/checkReducer.tsx
  FE/src/login/Login.tsx
  FE/src/mocks/handlers.ts
  FE/src/mocks/issueFilterOptions.js
  FE/src/pages/IssueListPage.tsx
  FE/src/pages/LoginPage.tsx
  FE/src/utils.ts
Labels: FE, feat, refactor

#49 Feature 48 3주차 수요일 리뷰 반영
  FE/config/webpack.common.js
  FE/src/App.tsx
  FE/src/common/components/Layout.tsx
  FE/src/common/components/Tab.tsx
  FE/src/common/components/TextInput.tsx
  FE/src/common/components/buttons/Button.tsx
  FE/src/common/components/buttons/ButtonSmallStandard.tsx
  FE/src/common/components/dropDown/DropDownCheckBoxItem.tsx
  FE/src/common/components/dropDown/DropDownPanel.tsx
  FE/src/common/constants/index.ts
  FE/src/common/constants/path.ts
  FE/src/common/utils/index.ts
  FE/src/common/utils/time.ts
  FE/src/issueList/FilterBar.tsx
  FE/src/issueList/LinkTabs.tsx
  FE/src/issueList/issueListTable/CheckBox.tsx
  FE/src/issueList/issueListTable/IssueList.tsx
  FE/src/issueList/issueListTable/issueHeader/ClickedIssueHeader.tsx
  FE/src/issueList/issueListTable/issueHeader/IssueHeader.tsx
  FE/src/issueList/issueListTable/issueHeader/IssueMenu.tsx
  FE/src/issueList/issueListTable/issueHeader/IssueTab.tsx
  FE/src/issueList/issueListTable/issueItem/EmptyIssueItem.tsx
  FE/src/issueList/issueListTable/issueItem/IssueItem.tsx
  FE/src/issueList/stores/checkReducer.tsx
  FE/src/login/Login.tsx
  FE/src/pages/IssueListPage.tsx
  FE/tsconfig.json
Labels: FE, refactor

#51 Feature 50 이슈 목록 체크한 이슈 아이템 상태 변경
  FE/src/issueList/issueListTable/issueHeader/ClickedIssueHeader.tsx
  FE/src/issueList/issueListTable/issueHeader/IssueTab.tsx
  FE/src/issueList/issueListTable/issueHeader/StatusIssueTab.tsx
  FE/src/issueList/stores/checkReducer.tsx
Labels: FE, feat, refactor
